spring.application.name=car-sharing-service
spring.datasource.url=jdbc:mysql://localhost:3306/car_sharing?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=svitlana
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
jwt.secret=donotworrybehappy12345magic6789moment0
jwt.expiration=3600000
stripe.api.key=sk_test_51S2xEZRBGZX2E0I1gFYAWl5ftmCjVIdkCtiQ3\
  oFFCNWnrf81cNKClyJGLvS3ipQC7eyqkyc40xOlKWax34blBLSp00eeNAvGOq
stripe.success.url=http://localhost:8080/payments/success
stripe.cancel.url=http://localhost:8080/payments/cancel
